### PR TITLE
Adding second version of yaml files for AMQ.

### PR DESCRIPTION
**Pull request by SvetlanaRedHat**
some yamls files has been changed in original github project, adding them as a v2
https://github.com/strimzi/strimzi-kafka-operator

### CODE REVIEW

**Comment by vasukulkarni** [comment]
@SvetlanaRedHat what about updating the amq script in ocs-ci?

**Comment by SvetlanaRedHat** [comment]
https://github.com/red-hat-storage/ocs-ci/pull/1963

**Comment by ramkiperiy** [comment]
Just a naive comment, don't have much idea about AMQ. If the yamls are going to be used without making any changes why not clone the yaml files to dir and continue deployment ?

**Comment by SvetlanaRedHat** [comment]
@ramkiperiy  Vasue wanted to have yaml files in separate github projects. just to avoid our main project tp be full with yaml files only

**Comment by vasukulkarni** [comment]
> Just a naive comment, don't have much idea about AMQ. If the yamls are going to be used without making any changes why not clone the yaml files to dir and continue deployment ?

I think originally there was some change, but if in v2 there is no change, we can probably clone from the main repo.

**Pull request merged**
